
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 08 14:55:12 AST 2020
//----------------------------------------------------

package ide;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 18;
  public static final int Clase = 25;
  public static final int Parentesis_a = 17;
  public static final int Suma = 9;
  public static final int Numero = 23;
  public static final int Op_booleano = 16;
  public static final int ERROR = 24;
  public static final int Identificador = 22;
  public static final int Comillas = 3;
  public static final int Int = 5;
  public static final int Llave_c = 20;
  public static final int Llave_a = 19;
  public static final int Op_relacional = 14;
  public static final int P_coma = 21;
  public static final int T_dato = 4;
  public static final int Cadena = 6;
  public static final int EOF = 0;
  public static final int Division = 12;
  public static final int Op_atribucion = 15;
  public static final int Resta = 10;
  public static final int If = 7;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Op_logico = 13;
  public static final int Igual = 8;
  public static final int Multiplicacion = 11;
}

