
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 09 01:16:59 AST 2020
//----------------------------------------------------

package ide;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 13;
  public static final int Clase = 19;
  public static final int Parentesis_a = 12;
  public static final int Suma = 5;
  public static final int Numero = 2;
  public static final int Imprimir = 17;
  public static final int Op_booleano = 11;
  public static final int ERROR = 23;
  public static final int Identificador = 3;
  public static final int Int = 18;
  public static final int Llave_c = 15;
  public static final int Llave_a = 14;
  public static final int Op_relacional = 10;
  public static final int P_coma = 16;
  public static final int EOF = 0;
  public static final int Retorna = 20;
  public static final int Division = 8;
  public static final int If = 22;
  public static final int Resta = 6;
  public static final int Potencia = 9;
  public static final int Flecha = 21;
  public static final int error = 1;
  public static final int Igual = 4;
  public static final int Multiplicacion = 7;
}

